copyright: 2023 Content provided by c01dkit
docs_dir: docs
markdown_extensions:
  toc:
    toc_depth: 0
nav:
- All: index.md
- IEEE S&P:
  - '2023': oakland_2023.md
  - '2022': oakland_2022.md
  - '2021': oakland_2021.md
  - '2020': oakland_2020.md
  - '2019': oakland_2019.md
- ACM CCS:
  - '2022': ccs_2022.md
  - '2021': ccs_2021.md
  - '2020': ccs_2020.md
  - '2019': ccs_2019.md
- USENIX Sec:
  - 2023_summer: usenix_security_2023_summer.md
  - 2023_fall: usenix_security_2023_fall.md
  - 2022_summer: usenix_security_2022_summer.md
  - 2022_fall: usenix_security_2022_fall.md
  - 2022_winter: usenix_security_2022_winter.md
  - 2021_summer: usenix_security_2021_summer.md
  - 2021_fall: usenix_security_2021_fall.md
  - 2020_spring: usenix_security_2020_spring.md
  - 2020_summer: usenix_security_2020_summer.md
  - 2020_fall: usenix_security_2020_fall.md
  - 2019_fall: usenix_security_2019_fall.md
- NDSS:
  - '2023': ndss_2023.md
  - '2022': ndss_2022.md
  - '2021': ndss_2021.md
  - '2020': ndss_2020.md
  - '2019': ndss_2019.md
- ICSE:
  - '2023': icse_2023.md
  - '2022': icse_2022.md
  - '2021': icse_2021.md
  - '2020': icse_2020.md
  - '2019': icse_2019.md
- ISSTA:
  - '2022': issta_2022.md
  - '2021': issta_2021.md
  - '2020': issta_2020.md
  - '2019': issta_2019.md
  - '2018': issta_2018.md
repo_url: https://github.com/c01dkit/sec-papers-collection
site_author: c01dkit
site_name: Collection of Security Papers
site_url: https://sec.c01dkit.com
theme:
  features:
  - content.code.copy
  - content.code.annotate
  name: material
