copyright: 2023 Content provided by c01dkit
docs_dir: docs
markdown_extensions:
- attr_list
- md_in_html
- pymdownx.superfences
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
nav:
- All: index.md
- NDSS:
  - '2023': ndss_2023.md
  - '2022': ndss_2022.md
  - '2021': ndss_2021.md
- ACM CCS:
  - '2022': ccs_2022.md
  - '2021': ccs_2021.md
- IEEE S&P:
  - '2023': oakland_2023.md
  - '2022': oakland_2022.md
  - '2021': oakland_2021.md
- USENIX Sec:
  - 2023_summer: usenix_security_2023_summer.md
  - 2023_fall: usenix_security_2023_fall.md
  - 2022_summer: usenix_security_2022_summer.md
  - 2022_fall: usenix_security_2022_fall.md
  - 2022_winter: usenix_security_2022_winter.md
repo_url: https://github.com/c01dkit/sec-papers-collection
site_author: c01dkit
site_name: Collection of Security Papers
site_url: https://sec.c01dkit.com
theme:
  features:
  - content.code.copy
  - content.code.annotate
  name: material
