copyright: 2024 Content provided by c01dkit
docs_dir: docs
markdown_extensions:
  toc:
    toc_depth: 0
nav:
- All: index.md
- IEEE S&P:
  - '2024': oakland_2024.md
  - '2023': oakland_2023.md
  - '2022': oakland_2022.md
  - '2021': oakland_2021.md
  - '2020': oakland_2020.md
  - '2019': oakland_2019.md
  - '2018': oakland_2018.md
  - '2017': oakland_2017.md
  - '2016': oakland_2016.md
  - '2015': oakland_2015.md
- ACM CCS:
  - '2023': ccs_2023.md
  - '2022': ccs_2022.md
  - '2021': ccs_2021.md
  - '2020': ccs_2020.md
  - '2019': ccs_2019.md
  - '2018': ccs_2018.md
  - '2017': ccs_2017.md
  - '2016': ccs_2016.md
  - '2015': ccs_2015.md
- USENIX Sec:
  - '2024': usenix_security_2024.md
  - '2023': usenix_security_2023.md
  - '2022': usenix_security_2022.md
  - '2021': usenix_security_2021.md
  - '2020': usenix_security_2020.md
  - '2019': usenix_security_2019.md
  - '2018': usenix_security_2018.md
  - '2017': usenix_security_2017.md
  - '2016': usenix_security_2016.md
  - '2015': usenix_security_2015.md
- NDSS:
  - '2024': ndss_2024.md
  - '2023': ndss_2023.md
  - '2022': ndss_2022.md
  - '2021': ndss_2021.md
  - '2020': ndss_2020.md
  - '2019': ndss_2019.md
  - '2018': ndss_2018.md
  - '2017': ndss_2017.md
  - '2016': ndss_2016.md
  - '2015': ndss_2015.md
- ICSE:
  - '2024': icse_2024.md
  - '2023': icse_2023.md
  - '2022': icse_2022.md
  - '2021': icse_2021.md
  - '2020': icse_2020.md
  - '2019': icse_2019.md
  - '2018': icse_2018.md
  - '2017': icse_2017.md
  - '2016': icse_2016.md
  - 2015-1: icse_2015-1.md
  - 2015-2: icse_2015-2.md
- ISSTA:
  - '2023': issta_2023.md
  - '2022': issta_2022.md
  - '2021': issta_2021.md
  - '2020': issta_2020.md
  - '2019': issta_2019.md
  - '2018': issta_2018.md
  - '2017': issta_2017.md
  - '2016': issta_2016.md
  - '2015': issta_2015.md
repo_url: https://github.com/c01dkit/sec-papers-collection
site_author: c01dkit
site_name: Collection of Security Papers
site_url: https://sec.c01dkit.com
theme:
  features:
  - content.code.copy
  - content.code.annotate
  name: material
