copyright: 2023 Content provided by c01dkit
docs_dir: docs
markdown_extensions:
  toc:
    toc_depth: 0
nav:
- All: index.md
- IEEE S&P:
  - '2023': oakland_2023.md
  - '2022': oakland_2022.md
  - '2021': oakland_2021.md
  - '2020': oakland_2020.md
  - '2019': oakland_2019.md
  - '2018': oakland_2018.md
- ACM CCS:
  - '2022': ccs_2022.md
  - '2021': ccs_2021.md
  - '2020': ccs_2020.md
  - '2019': ccs_2019.md
  - '2018': ccs_2018.md
- USENIX Sec:
  - '2023': usenix_security_2023.md
  - '2022': usenix_security_2022.md
  - '2021': usenix_security_2021.md
  - '2020': usenix_security_2020.md
  - '2019': usenix_security_2019.md
  - '2018': usenix_security_2018.md
- NDSS:
  - '2023': ndss_2023.md
  - '2022': ndss_2022.md
  - '2021': ndss_2021.md
  - '2020': ndss_2020.md
  - '2019': ndss_2019.md
  - '2018': ndss_2018.md
- ICSE:
  - '2023': icse_2023.md
  - '2022': icse_2022.md
  - '2021': icse_2021.md
  - '2020': icse_2020.md
  - '2019': icse_2019.md
  - '2018': icse_2018.md
- ISSTA:
  - '2023': issta_2023.md
  - '2022': issta_2022.md
  - '2021': issta_2021.md
  - '2020': issta_2020.md
  - '2019': issta_2019.md
  - '2018': issta_2018.md
repo_url: https://github.com/c01dkit/sec-papers-collection
site_author: c01dkit
site_name: Collection of Security Papers
site_url: https://sec.c01dkit.com
theme:
  features:
  - content.code.copy
  - content.code.annotate
  name: material
